name: flutter_mrmilu
description: Mr Milú's official shared package for Flutter projects
version: 1.1.0
issue_tracker: https://github.com/mrmilu/flutter_mrmilu/issues
repository: https://github.com/mrmilu/flutter_mrmilu

environment:
  sdk: ">=2.19.1 <3.0.0"
  flutter: ">=3.7.1"

dependencies:
  dio: 5.0.3
  flutter:
    sdk: flutter
  intl: 0.18.0
  meta: 1.8.0
  url_launcher: 6.1.10
  faker_dart: 0.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  index_generator: 3.3.3
  http_mock_adapter: 0.4.2

flutter:


## Index generator configuration
index_generator:
  exclude:
    - '**/helpers_io.dart'
    - '**/helpers_web.dart'
  indexes:
    - path: lib
      name: flutter_mrmilu
      library: flutter_mrmilu
      docs: |
        Mr Milú Flutter library