name: flutter_mrmilu
description: Mr Milú's official shared package for Flutter projects
version: 1.0.0
issue_tracker: https://github.com/mrmilu/flutter_mrmilu/issues
repository: https://github.com/mrmilu/flutter_mrmilu

environment:
  sdk: ">=2.19.1 <3.0.0"
  flutter: ">=3.7.1"

dependencies:
  dio: 4.0.6
  flutter:
    sdk: flutter
  intl: 0.17.0
  meta: 1.8.0
  url_launcher: 6.1.9
  faker_dart: 0.1.11
  firebase_messaging: 14.2.1
  flutter_local_notifications: 13.0.0
  google_sign_in: 5.4.4
  sign_in_with_apple: 4.3.0
  crypto: 3.0.2
  firebase_auth: 4.2.5
  flutter_image_compress: 1.1.3
  image_picker: 0.8.6+1
  path_provider: 2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  index_generator: 3.3.3
  http_mock_adapter: 0.3.3

flutter:


## Index generator configuration
index_generator:
  exclude:
    - '**/helpers_io.dart'
    - '**/helpers_web.dart'
  indexes:
    - path: lib
      name: flutter_mrmilu
      library: flutter_mrmilu
      docs: |
        Mr Milú Flutter library