name: flutter_mrmilu
description: Mr Milú's official shared package for Flutter projects
version: 0.2.2
issue_tracker: https://github.com/mrmilu/flutter_mrmilu/issues
repository: https://github.com/mrmilu/flutter_mrmilu

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: 4.0.4
  flutter:
    sdk: flutter
  intl: 0.17.0
  meta: 1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4
  index_generator: 3.0.0
  faker_dart: 0.1.4
  http_mock_adapter: ^0.3.3

flutter:


## Index generator configuration
index_generator:
  exclude:
    - '**/helpers_io.dart'
    - '**/helpers_web.dart'
  indexes:
    - path: lib
      name: flutter_mrmilu
      library: flutter_mrmilu