name: flutter_mrmilu
description: Package with common utilities for all Mr Milú projects
version: 0.0.1
issue_tracker: https://github.com/mrmilu/flutter_mrmilu/issues
repository: https://github.com/mrmilu/flutter_mrmilu

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4

flutter:
